[tool.poetry]
name = "greatlibrarian"
version = "0.0.2"
description = ""
authors = ["dmj <ggxxding@163.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
zhipuai = "^1.0.7"
pandas = "^2.1.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
gltest = "greatlibrarian.run:main"